[CmdletBinding()]
param(
  [ValidateSet("Preview","Quarantine","Restore","Purge")][string]$Mode="Preview",
  [string]$PlanPath="",
  [string]$RunId="",
  [string]$Confirm="",
  [ValidateRange(3,3650)][int]$MinimumAgeDays=7,
  [switch]$Synthetic
)
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"

# Geumyi Day 1-12 PC temp cleanup. Never inspect server roots for deletion.
# No mutation to world/backup/cache/installed GSC or GSCM directories.
$stateRoot=Join-Path ([Environment]::GetFolderPath("LocalApplicationData")) "Geumyi-Day1To12-Cleanup"
$plansRoot=Join-Path $stateRoot "Plans"
$quarantineRoot=Join-Path $stateRoot "Quarantine"
$reportsRoot=Join-Path ([Environment]::GetFolderPath("Desktop")) "Geumyi-Day1To12-Cleanup-Reports"
$now=[DateTime]::UtcNow

function Full([string]$Path){
  return [IO.Path]::GetFullPath($Path).TrimEnd('\')
}
function Within([string]$Path,[string]$Parent){
  $p=Full $Path;$root=Full $Parent
  return $p.StartsWith(($root+'\'),[StringComparison]::OrdinalIgnoreCase)
}
function Has-Reparse([object]$Item){
  return (([int]$Item.Attributes -band [int][IO.FileAttributes]::ReparsePoint) -ne 0)
}
function Day-FromName([string]$Name){
  $m=[regex]::Match($Name,'^(?i:Geumyi[-_])?Day(?<day>[1-9]|1[0-2])(?=[-_])')
  if($m.Success){return [int]$m.Groups["day"].Value}
  if($Name -match '^(?i:Geumyi[-_])?(?:FourPortTest|FourServerTest)[-_]'){return 10}
  if($Name -match '^(?i:gscm_flutter_template_)[a-f0-9-]{8,}$'){return 0}
  return -1
}
function Known-TempName([string]$Name,[int]$Day){
  if($Day -lt 0){return $false}
  if($Day -eq 0){return $true} # temp-only Flutter template generated by GSCM tools
  if($Name -match '^(?i:Geumyi[-_])Day(?:[1-9]|1[0-2])[-_]'){return $true}
  if($Name -match '^(?i:Day)(?:8|9|10|11|12)[-_](?:Final|Stage|Phase|Preflight|Readiness|FourServer|FourCI|RollbackSynthetic|Recovery|Recovery-Test|SelfTest|Stage-Test)'){return $true}
  if($Name -match '^(?i:Geumyi[-_])?(?:FourPortTest|FourServerTest)[-_]'){return $true}
  return $false
}
function Protected-Name([string]$Name){
  if($Name -match '^(?i:world(?:_nether|_the_end)?|worlds|saves|playerdata|data|region|DIM-1|DIM1|backups?|golden(?:[-_].*)?|recovery|restore|rollback|restorepoints?|artifactcache|known-good|cache|logs?|crash-reports|plugins|mods|datapacks|resourcepacks|database|secrets?|keys?|credentials?|tokens?|\.git)$'){return $true}
  if($Name -match '(?i)(?:^|[._-])(?:backup|golden|rollback|restore|world|secret|token|private-key)(?:[._-]|$)'){return $true}
  if($Name -match '(?i)\.(?:jar|mcworld|mca|db|sqlite|sqlite3|pem|pfx|key|jks|keystore|log|dmp|dump)$'){return $true}
  if($Name -match '^(?i:server\.json|server\.properties|config\.yml|bukkit\.yml|spigot\.yml|paper-global\.yml|eula\.txt)$'){return $true}
  return $false
}
function Get-Roots {
  $roots=@()
  foreach($v in @($env:TEMP,$env:TMP,(Join-Path $env:LOCALAPPDATA "Temp"))){
    if([string]::IsNullOrWhiteSpace($v)){continue}
    try{
      if(-not(Test-Path -LiteralPath $v -PathType Container)){continue}
      $f=Full $v
      if($roots -notcontains $f){$roots+= $f}
    }catch{}
  }
  return @($roots)
}
function Inspect-Candidate([string]$Path,[int]$Day,[int]$MinAge,[string]$Scope){
  $o=[ordered]@{
    path=$Path;day=$Day;scope=$Scope;category="TEMP_WORKSPACE"
    eligible=$false;reason="UNASSESSED";kind="UNKNOWN"
    bytes=[int64]0;file_count=0;newest_ticks=[int64]0;items_count=0
  }
  try{
    $item=Get-Item -LiteralPath $Path -Force -ErrorAction Stop
    $o.kind=if($item.PSIsContainer){"DIRECTORY"}else{"FILE"}
    if($Scope -ne "TEMP"){$o.reason="INVENTORY_ONLY_DESKTOP_DOWNLOADS";return $o}
    if($Day -eq 12){$o.reason="DAY12_CLOSURE_NOT_VERIFIED";return $o}
    if(Has-Reparse $item){$o.reason="REPARSE_POINT";return $o}
    if($Day -eq 0){$o.reason="GSCM_TEMPLATE_MANUAL_REVIEW";return $o}
    if($item.LastWriteTimeUtc -gt $now.AddDays(-$MinAge)){
      $o.reason="TOO_RECENT";return $o
    }
    $total=[int64]0;$count=0;$newest=$item.LastWriteTimeUtc
    $list=@($item)
    if($item.PSIsContainer){
      $list=@(Get-ChildItem -LiteralPath $Path -Recurse -Force -ErrorAction Stop)
    }
    foreach($child in $list){
      $count++
      if($count -gt 10000){$o.reason="TOO_MANY_ITEMS";return $o}
      if(Has-Reparse $child){$o.reason="NESTED_REPARSE_POINT";return $o}
      if(Protected-Name $child.Name){$o.reason="PROTECTED_CONTENT";return $o}
      if($child.LastWriteTimeUtc -gt $newest){$newest=$child.LastWriteTimeUtc}
      if(-not $child.PSIsContainer){$total+=[int64]$child.Length}
      if($total -gt 1GB){$o.reason="TOO_LARGE";return $o}
    }
    $o.newest_ticks=[int64]$newest.Ticks
    $o.bytes=$total;$o.file_count=@($list|Where-Object{-not $_.PSIsContainer}).Count
    $o.items_count=$count
    if($newest -gt $now.AddDays(-$MinAge)){$o.reason="RECENT_NESTED_FILE";return $o}
    if(-not $item.PSIsContainer){$o.reason="SINGLE_FILE_MANUAL_REVIEW";return $o}
    $o.eligible=$true;$o.reason="ELIGIBLE_OLD_TEMP_DIRECTORY"
    return $o
  }catch{$o.reason="READ_ERROR_OR_ACCESS_DENIED";return $o}
}
function Report([object]$Data,[string]$Type){
  New-Item -Path $reportsRoot -ItemType Directory -Force|Out-Null
  $target=Join-Path $reportsRoot ($Type+"-"+(Get-Date -Format "yyyyMMdd-HHmmss")+".json")
  $Data|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $target -Encoding UTF8
  Write-Host ("Report saved: "+$target)
  return $target
}
function Validate-RunId([string]$Id){
  if($Id -notmatch '^[0-9]{8}-[0-9]{6}-[a-f0-9]{8}$'){throw "Invalid cleanup run ID"}
}
function Read-Manifest([string]$Id){
  Validate-RunId $Id
  $path=Join-Path (Join-Path $quarantineRoot $Id) "manifest.json"
  if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "No local quarantine manifest for run"}
  return (Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json)
}
function Checked-Plan([string]$Path){
  if([string]::IsNullOrWhiteSpace($Path)){throw "PlanPath from Preview is required"}
  if(-not(Within $Path $plansRoot)){throw "Plan must be inside local Geumyi cleanup Plans"}
  if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "Plan file missing"}
  return (Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json)
}
if($Synthetic){
  # Tests only model decisions and safety guards; never touch the operator PC.
  $case1=Known-TempName "Geumyi-Day8-Final" (Day-FromName "Geumyi-Day8-Final")
  $case2=Known-TempName "Day10-Phase1" (Day-FromName "Day10-Phase1")
  $case3=(Day-FromName "Geumyi-Day12-Native-TCP") -eq 12
  $case4=(Day-FromName "MyTaxes-2026") -eq -1
  $case5=Protected-Name "world_nether"
  $case6=Protected-Name "server.json"
  $case7=Protected-Name "day12-golden.zip"
  $case8=(-not (Protected-Name "output.tmp"))
  $case9=(Day-FromName "gscm_flutter_template_abcdef123456") -eq 0
  if(-not($case1 -and $case2 -and $case3 -and $case4 -and $case5 -and $case6 -and $case7 -and $case8 -and $case9)){
    throw "Cleanup classifier synthetic regression"
  }
  Write-Host "Geumyi day1-12 cleanup classifier synthetic PASS"
  exit 0
}
# Real modes: inventory and plan under user temp, any permanent deletion only
# via verified quarantine RunId after 14 days and explicit confirmation.
if($Mode -eq "Preview"){
  New-Item -ItemType Directory -Path $plansRoot -Force|Out-Null
  $list=@();$roots=@(Get-Roots)
  foreach($root in $roots){
    foreach($f in @(Get-ChildItem -LiteralPath $root -Force -ErrorAction SilentlyContinue)){
      $day=Day-FromName $f.Name
      if(-not(Known-TempName $f.Name $day)){continue}
      $list+=Inspect-Candidate $f.FullName $day $MinimumAgeDays "TEMP"
    }
  }
  # Surface leftovers on Desktop and Downloads without allowing mutation.
  $userRoot=[Environment]::GetFolderPath("UserProfile")
  foreach($location in @([Environment]::GetFolderPath("Desktop"),(Join-Path $userRoot "Downloads"))){
    if(-not(Test-Path -LiteralPath $location -PathType Container)){continue}
    foreach($f in @(Get-ChildItem -LiteralPath $location -Force -ErrorAction SilentlyContinue)){
      $day=Day-FromName $f.Name
      if(-not(Known-TempName $f.Name $day)){continue}
      $list+=Inspect-Candidate $f.FullName $day $MinimumAgeDays "INVENTORY_ONLY"
    }
  }
  $id=(Get-Date -Format "yyyyMMdd-HHmmss")+"-"+[guid]::NewGuid().ToString("N").Substring(0,8)
  $plan=[ordered]@{schema=1;created_utc=$now.ToString("o");minimum_age_days=$MinimumAgeDays
    run_id=$id;roots=$roots;items=$list
    notice="PRIVATE LOCAL PLAN: contains original paths. Do not upload this file."}
  $planFile=Join-Path $plansRoot ("plan-"+$id+".json")
  $plan|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $planFile -Encoding UTF8
  $eligible=@($list|Where-Object{$_.eligible})
  $sum=[int64]0;foreach($x in $eligible){$sum+=[int64]$x.bytes}
  $summary=@()
  foreach($x in $list){
    $summary+= [ordered]@{day=$x.day;scope=$x.scope;reason=$x.reason
      eligible=[bool]$x.eligible;size_bytes=[int64]$x.bytes;files=[int]$x.file_count}
  }
  [void](Report ([ordered]@{schema=1;mode="PREVIEW";read_only=$true;run_id=$id
      created_utc=$now.ToString("o");minimum_age_days=$MinimumAgeDays
      candidates=$list.Count;eligible=$eligible.Count
      eligible_bytes=$sum;inventory=$summary
      notes=@("Private plan saved locally, never upload plan.json.",
        "Desktop and Downloads are INVENTORY ONLY; no deletion supported.",
        "DAY12 artifacts are HOLD until final closure gates PASS.",
        "Only approved old named temp directories may move into recoverable quarantine.",
        "No Windows Update, Prefetch, Recycle Bin, global Temp, backup, world, plugin, cache or installed GSC data is cleared.")}) "Day1To12-Cleanup-Preview")
  Write-Host ("Private plan (keep local): "+$planFile)
  Write-Host ("Candidates: "+$list.Count+"; quarantine-eligible: "+$eligible.Count+"; bytes: "+$sum)
  Write-Host "No files moved or deleted. To quarantine use -Mode Quarantine -PlanPath <path> -Confirm QUARANTINE_GEUMYI_TEMP"
  exit 0
}
if($Mode -eq "Quarantine"){
  if($Confirm -cne "QUARANTINE_GEUMYI_TEMP"){throw "Explicit quarantine confirmation required"}
  $plan=Checked-Plan $PlanPath
  if([int]$plan.schema -ne 1){throw "Unsupported plan schema"}
  if(([DateTime]::UtcNow-[DateTime]::Parse([string]$plan.created_utc).ToUniversalTime()).TotalHours -gt 24){throw "Plan older than 24 hours; rerun Preview"}
  $id=[string]$plan.run_id;Validate-RunId $id
  $destDir=Join-Path $quarantineRoot $id
  if(Test-Path -LiteralPath $destDir){throw "Quarantine run already exists"}
  New-Item -ItemType Directory -Force -Path $destDir|Out-Null
  $moved=@();$skipped=@();$idx=0
  $roots=@(Get-Roots)
  # Write the local restore journal before moving the first candidate.
  # Each recorded move is flushed to disk to tolerate partial operations.
  $manifestPath=Join-Path $destDir "manifest.json"
  $manifest=[ordered]@{schema=1;run_id=$id;created_utc=$now.ToString("o")
    items=@();skipped_reasons=@()
    note="PRIVATE LOCAL MANIFEST: contains source paths; needed for restore."}
  $manifest|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $manifestPath -Encoding UTF8
  foreach($p in @($plan.items)){
    $idx++
    if(-not [bool]$p.eligible){continue}
    $origin=[string]$p.path
    if(-not(Test-Path -LiteralPath $origin -PathType Container)){$skipped+="SOURCE_MISSING";continue}
    $actualParent=Full (Split-Path -Parent $origin)
    if($roots -notcontains $actualParent -or $actualParent -notin @($plan.roots)){$skipped+="TEMP_ROOT_CHANGED";continue}
    if($origin -notlike '*Day*'){$skipped+="NAME_REJECTED";continue}
    $day=Day-FromName ([IO.Path]::GetFileName($origin))
    if($day -le 0 -or $day -gt 11 -or -not (Known-TempName ([IO.Path]::GetFileName($origin)) $day)){$skipped+="DAY_OR_NAME_REJECTED";continue}
    $fresh=Inspect-Candidate $origin $day ([int]$plan.minimum_age_days) "TEMP"
    if(-not $fresh.eligible -or $fresh.items_count -ne [int]$p.items_count -or
       $fresh.bytes -ne [int64]$p.bytes -or $fresh.newest_ticks -ne [int64]$p.newest_ticks){
       $skipped+="CHANGED_OR_PROTECTED";continue
    }
    $dest=Join-Path $destDir ("item-"+$idx.ToString("D4"))
    if(Test-Path -LiteralPath $dest){$skipped+="DESTINATION_EXISTS";continue}
    try{
      # Require same drive for atomic directory rename, not copy+delete.
      if([IO.Path]::GetPathRoot($origin) -ine [IO.Path]::GetPathRoot($dest)){
        $skipped+="DIFFERENT_VOLUME";continue
      }
      $journalRow=[ordered]@{ordinal=$idx;original=$origin;stored=$dest
        bytes=[int64]$p.bytes;day=[int]$day;restored=$false}
      # Crash-safe PRE-JOURNAL: a move interrupted after filesystem rename
      # remains discoverable by Restore via its manifest record.
      $manifest.items=@($moved)+@($journalRow)
      $manifest|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $manifestPath -Encoding UTF8
      Move-Item -LiteralPath $origin -Destination $dest -ErrorAction Stop
      $moved+= $journalRow
    }catch{
      if(-not(Test-Path -LiteralPath $dest -PathType Container)){
        $manifest.items=@($moved)
      }else{
        # An interrupted move may have succeeded; keep its recovery journal.
        if(@($moved|Where-Object{$_.stored -eq $dest}).Count -eq 0){$moved+= $journalRow}
        $manifest.items=@($moved)
      }
      $skipped+="LOCKED_OR_MOVE_FAILED"
    }
  }
  $manifest.items=@($moved);$manifest.skipped_reasons=@($skipped)
  $manifest|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $manifestPath -Encoding UTF8
  $sum=[int64]0;foreach($i in $moved){$sum+=[int64]$i.bytes}
  [void](Report ([ordered]@{schema=1;mode="QUARANTINE";run_id=$id
      moved=$moved.Count;estimated_bytes=$sum;skipped=$skipped.Count
      skipped_reasons=@($skipped);recoverable=$true;permanent_deletion=$false}) "Day1To12-Cleanup-Quarantine")
  Write-Host ("Quarantine run: "+$id+"; moved: "+$moved.Count+"; skipped: "+$skipped.Count)
  Write-Host "No permanent deletion. Restore with -Mode Restore -RunId <id> -Confirm RESTORE_GEUMYI_TEMP"
  exit 0
}
if($Mode -eq "Restore"){
  if($Confirm -cne "RESTORE_GEUMYI_TEMP"){throw "Restore confirmation required"}
  $manifest=Read-Manifest $RunId
  $restored=0;$skipped=0
  foreach($entry in @($manifest.items)){
    if([bool]$entry.restored){continue}
    $stored=[string]$entry.stored;$origin=[string]$entry.original
    if(-not(Within $stored (Join-Path $quarantineRoot $RunId))){$skipped++;continue}
    if(-not(Test-Path -LiteralPath $stored -PathType Container)){$skipped++;continue}
    if(Test-Path -LiteralPath $origin){$skipped++;continue} # never overwrite
    $root=Full (Split-Path -Parent $origin)
    if(@(Get-Roots) -notcontains $root){$skipped++;continue}
    if(Has-Reparse (Get-Item -LiteralPath $stored -Force)){$skipped++;continue}
    try{
      Move-Item -LiteralPath $stored -Destination $origin -ErrorAction Stop
      $entry.restored=$true
      $restored++
    }catch{$skipped++}
  }
  $manifest|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path (Join-Path $quarantineRoot $RunId) "manifest.json") -Encoding UTF8
  [void](Report ([ordered]@{schema=1;mode="RESTORE";run_id=$RunId;restored=$restored;skipped=$skipped}) "Day1To12-Cleanup-Restore")
  Write-Host ("Restored: "+$restored+"; skipped: "+$skipped)
  exit 0
}
if($Mode -eq "Purge"){
  if($Confirm -cne "PURGE_GEUMYI_QUARANTINE_14D"){throw "Explicit permanent purge confirmation required"}
  $manifest=Read-Manifest $RunId
  if(([DateTime]::UtcNow-[DateTime]::Parse([string]$manifest.created_utc).ToUniversalTime()).TotalDays -lt 14){
    throw "Quarantine must be retained at least 14 days before permanent purge"
  }
  $folder=Join-Path $quarantineRoot $RunId
  $eligible=@($manifest.items|Where-Object{-not [bool]$_.restored})
  foreach($entry in $eligible){
    if(-not(Within ([string]$entry.stored) $folder)){throw "Stored path outside run quarantine"}
    $target=[string]$entry.stored
    if(-not(Test-Path -LiteralPath $target -PathType Container)){continue}
    $sub=@(Get-ChildItem -LiteralPath $target -Recurse -Force -ErrorAction Stop)
    if(Has-Reparse (Get-Item -LiteralPath $target -Force)){throw "Reparse directory blocked"}
    if(@($sub|Where-Object{Has-Reparse $_}).Count -gt 0){throw "Reparse subtree blocked"}
  }
  $purged=0
  foreach($entry in $eligible){
    $target=[string]$entry.stored
    if(Test-Path -LiteralPath $target -PathType Container){
      Remove-Item -LiteralPath $target -Recurse -Force -ErrorAction Stop
      $purged++
    }
  }
  # Keep the manifest and audit report, only remove individually isolated items.
  $manifest|Add-Member -NotePropertyName "purged_utc" -NotePropertyValue ([DateTime]::UtcNow.ToString("o")) -Force
  $manifest|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $folder "manifest.json") -Encoding UTF8
  [void](Report ([ordered]@{schema=1;mode="PURGE";run_id=$RunId;deleted_quarantined_items=$purged
    warning="Permanent deletion of quarantined items only; manifest/audit retained"}) "Day1To12-Cleanup-Purge")
  Write-Host ("Permanently removed quarantined items: "+$purged)
  exit 0
}
throw "Unexpected mode"
